// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_images_filename_ from "./routes/api/images/[filename].ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ramen_id_ from "./routes/ramen/[id].tsx";
import * as $ramen_new from "./routes/ramen/new.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $RamenForm from "./islands/RamenForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/images/[filename].ts": $api_images_filename_,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/ramen/[id].tsx": $ramen_id_,
    "./routes/ramen/new.tsx": $ramen_new,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/RamenForm.tsx": $RamenForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
